import { IsNotEmpty, IsOptional, IsString } from 'class-validator';
import { ApiProperty } from '@nestjs/swagger';

export class ConfirmPaymentDto {
  @ApiProperty({ description: 'Stripe Payment Method ID generated by the frontend elements link' })
  @IsString()
  @IsNotEmpty()
  paymentMethodId!: string;

  @ApiProperty({ description: 'Optional delivery notes or customer special instructions' })
  @IsString()
  @IsOptional()
  notes?: string;
}